services:
  # Ollama LLM Service
  ollama:
    image: ollama/ollama:0.3.11
    container_name: ollama
    expose:
      - "11434" 
    volumes:
      - podcast-data:/root/.ollama
    networks:
      - podcast-network

  grpc-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: llm
    ports:
      - "50051:50051"
    env_file:
      - ../.env
    networks:
      - podcast-network
    depends_on:
      - ollama

  # llm-service:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.src
  #   container_name: llm-service
  #   env_file:
  #     - ../.env
  #   networks:
  #     - podcast-network
  #   depends_on:
  #     - ollama
  #     - grpc-server
  #   volumes:
  #     - ../data:/app/data

volumes:
  podcast-data:
    external: true

networks:
  podcast-network:
    driver: bridge
    external: true